### ISSUE TITLE
What version of Tensorflow are you using and what models should I run?

### ISSUE THREAD

**Issue by damiankucharski** [YixingHuang/DeepMedicPlus#1]
Hello, thank you for your work, it looks very promising. I would like to ask you about the version of TensorFlow you used for this project. Apart from that I would like to ask about the specific commands to run the models as the commands in the readme seem to be not updated. Specifically, the model names in the repository do not reflect any name in the readme files.
@YixingHuang 
Regards,
DK

**Comment by YixingHuang** [comment]
Hi, our Tensorflow-GPU version is 2.4.1. 
Thank you for notifying me the old README file in the folder of the pretrained models @damiankucharski . Now the old one is deleted. Please read the [main README file at the beginning:](https://github.com/YixingHuang/DeepMedicPlus)

For example, for inference: 
```
python deepMedicRun -model ./examples/configFiles/deepMedicPlus/model/modelConfig_wide1_deeper.cfg -test ./examples/configFiles/deepMedicPlus/test/testConfig.cfg -load ./examples/output/saved_models/deepMedicWide1.high_sensitivity.model.ckpt -dev cuda0
```

**Comment by damiankucharski** [comment]
Hi, thank you for your response @YixingHuang.
In the ./examples/output/saved_models I see 
- deepMedicWide1.high_precision.model.ckpt.data-00000-of-00001
- deepMedicWide1.high_precision.model.ckpt.index

and similarly for the high sensitivity model. Should I use the second file? There is no file with the exact name you mentioned.

**Comment by YixingHuang** [comment]
@damiankucharski 
when you load the model name of deepMedicWide1.high_precision.model.ckpt, the corresponding two files with .data-00000-of-00001 and .index both will be loaded. The data file saves the weights of each variable and the index file saves all the variable information, such as variable names. The network graph can also be saved as .meta file. In DeepMedic, it is not saved. Therefore, you need to use the same architecture (specified by [modelConfig_wide1_deeper.cfg](https://github.com/YixingHuang/DeepMedicPlus/blob/main/DeepMedicPlus/examples/configFiles/deepMedicPlus/model/modelConfig_wide1_deeper.cfg) in our DeepMedic+) to load the model weights.

**Comment by damiankucharski** [comment]
Understood, thank you very much for your help, I will look into that.

**Comment by YixingHuang** [comment]
My pleasure. If you have further questions, feel free to open new issues. I have closed this one.
