### ISSUE TITLE
During training, the code refuses to save the predictions on the validation set

### ISSUE THREAD

**Issue by julclu** [YixingHuang/DeepMedicPlus#12]
Hello Yixing, 

See title. I can (seemingly) successfully train a model, but during training even if saveSegmentationVal=True, it will not populate the folders "predictions" in the output directory. I also can't get it to work with inference. Can you please advise? 

Thanks,
Julia

**Comment by YixingHuang** [comment]
Hi Julia,
I do not get your issue. The inference results should be in the folder of ".\examples\output\predictions\". To save time from validation, you can set saveSegmentationVal=False.
